language: emacs-lisp
sudo: false
before_install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > evm-travis.sh && source ./evm-travis.sh
  - evm install $EVM_EMACS --use --skip
  - cask
env:
  - EVM_EMACS=emacs-24.5-bin
script:
  ./run-travis-ci.sh
